export const icons = {
  user: "👤",
  server: "📊",
  members: "👥",
  owner: "👑",
  id: "🆔",
  bot: "🤖",
  calendar: "📅",
  join: "📥",
  success: "✅",
  error: "❌",
  warning: "⚠️",
  settings: "⚙️",
  shield: "🛡️",
} as const;